[package]
name = "TODO"
version = "0.1.0"
authors = ["marc gutenberger <gutenfries@gmail.com>"]

[dependencies]
clap = { version = "^2.0", features = ["yaml"] }
error-chain = "^0.10"
log = "^0.3"
env_logger = "^0.4"
colored = "^1.5"
