[package]
name = "fibber"
version = "0.1.0"
authors = ["marc gutenberger <gutenfries@gmail.com>"]

[dependencies]
clap = { version = "4.0.18", features = ["derive", "cargo"] }
once_cell = "1.8.0"

[[bin]]
name = "fibber"
path = "src/main.rs"
